// Package vtcapture wraps charmbracelet/x/vt to provide screen capture helpers.
package vtcapture

import (
	"bytes"
	"fmt"
	"strings"

	uv "github.com/charmbracelet/ultraviolet"
	"github.com/charmbracelet/x/vt"
)

// Terminal wraps a vt.Emulator and adds capture helpers.
type Terminal struct {
	emu *vt.Emulator
}

// NewTerminal creates a virtual terminal with the given dimensions.
func NewTerminal(cols, rows int) *Terminal {
	return &Terminal{emu: vt.NewEmulator(cols, rows)}
}

// Write feeds output bytes into the VT emulator.
func (t *Terminal) Write(p []byte) (int, error) {
	return t.emu.Write(p)
}

// Read reads replies generated by the VT emulator (e.g. OSC color-query
// responses). These bytes should be forwarded back to the child PTY.
func (t *Terminal) Read(p []byte) (int, error) {
	return t.emu.Read(p)
}

// Close closes the VT emulator and its internal input pipe.
func (t *Terminal) Close() error {
	return t.emu.Close()
}

// Resize changes the terminal size.
func (t *Terminal) Resize(cols, rows int) {
	t.emu.Resize(cols, rows)
}

// SetScrollbackSize limits the scrollback history.
func (t *Terminal) SetScrollbackSize(n int) {
	t.emu.SetScrollbackSize(n)
}

// Cursor returns the current cursor position (row, col).
func (t *Terminal) Cursor() (row, col int) {
	pos := t.emu.CursorPosition()
	return pos.Y, pos.X
}

// CaptureANSI returns an ANSI representation of the current screen.
func (t *Terminal) CaptureANSI() []byte {
	return []byte(t.emu.Render())
}

// CaptureText returns the plain text of the current screen.
func (t *Terminal) CaptureText() []byte {
	return []byte(t.emu.String())
}

// CaptureScrollbackANSI returns ANSI for the last n scrollback lines plus screen.
func (t *Terminal) CaptureScrollbackANSI(n int) []byte {
	var buf bytes.Buffer
	sb := t.emu.Scrollback()
	if sb != nil {
		lines := sb.Lines()
		start := len(lines) - n
		if start < 0 {
			start = 0
		}
		for i := start; i < len(lines); i++ {
			buf.Write(lineToANSI(lines[i]))
			buf.WriteByte('\n')
		}
	}
	buf.Write(t.CaptureANSI())
	return buf.Bytes()
}

// CaptureScrollbackText returns plain text for the last n scrollback lines plus screen.
func (t *Terminal) CaptureScrollbackText(n int) []byte {
	var buf bytes.Buffer
	sb := t.emu.Scrollback()
	if sb != nil {
		lines := sb.Lines()
		start := len(lines) - n
		if start < 0 {
			start = 0
		}
		for i := start; i < len(lines); i++ {
			buf.WriteString(lineToString(lines[i]))
			buf.WriteByte('\n')
		}
	}
	buf.Write(t.CaptureText())
	return buf.Bytes()
}

func lineToANSI(line []uv.Cell) []byte {
	var buf bytes.Buffer
	for _, cell := range line {
		// Best-effort ANSI reconstruction is complex; emit cell content only.
		buf.WriteString(cell.Content)
	}
	return buf.Bytes()
}

func lineToString(line []uv.Cell) string {
	var b strings.Builder
	for _, cell := range line {
		b.WriteString(cell.Content)
	}
	return b.String()
}

// CellAt returns the cell content at the given column and row.
func (t *Terminal) CellAt(col, row int) string {
	cell := t.emu.CellAt(col, row)
	if cell == nil {
		return ""
	}
	return cell.Content
}

// Size returns the current terminal size (cols, rows).
func (t *Terminal) Size() (cols, rows int) {
	return t.emu.Width(), t.emu.Height()
}

// String returns a debug representation of the current screen.
func (t *Terminal) String() string {
	return fmt.Sprintf("Terminal %dx%d cursor=(%d,%d)", t.emu.Width(), t.emu.Height(), t.emu.CursorPosition().X, t.emu.CursorPosition().Y)
}
